# Copy this to docker-compose.override.yml and modify as needed.  This file
# adds some dev-friendly container magic to the mix:
#
# - All binaries are mounted into the container so you can test out local changes
# - RAIS directly exposes its port to the host machine for quick debugging
#
# Note that docker-compose.override.yml is only automatically used if you
# *don't* specify a compose file.  e.g., `docker-compose up` will use
# docker-compose.yml and docker-compose.override.yml (if present).  But
# `docker-compose -f docker-compose.yml` will *not* use the override file.  If
# you wanted to use this with, for instance, datadog, you'd have to merge the
# datadog config with the overrides or else set up something like this:
#
#     alias ddog='docker-compose -f docker-compose.yml -f docker-compose.datadog.yml -f docker-compose.override.yml'
version: "3.4"
services:
  rais:
    # Uncomment this if you'd like to fire up an Alpine-based container - note
    # that it doesn't have any configuration baked in, so you'll have to use
    # environment vars for *all configuration*.  Good for production, but bad
    # for a quick demo.
    #image: uolibraries/rais:latest-alpine
    environment:
      # These next lines would allow you to pass the various S3 configuration
      # options through from the host's environment (or the local .env file)
      - RAIS_S3CACHE
      - RAIS_S3ZONE
      - RAIS_S3ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      # If you wanted to use a configured AWS credentials file for s3, do this
      # and then see the volume config below
      - AWS_SHARED_CREDENTIALS_FILE=/etc/aws.credentials
    volumes:
      # Mount in all binaries so you aren't rebuilding the image to test quick changes
      - ./bin:/opt/rais:ro
      # Volume config (modify source) for using an AWS credentials file
      - /home/myuser/.aws/credentials:/etc/aws.credentials
    ports:
      - 12415:12415
      - 12416:12416
